development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: db_dev

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: db_prod

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: db_test
